name: Run Build and Tests on Pull Request

on:
  pull_request:
    types: 
      - opened
      - reopened
      - synchronize

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: "lts/*"
    - run: npm install  --legacy-peer-deps
    - name: Run Tests
      run: |
        npx jest --ci --coverage --maxWorkers=2
      continue-on-error: false
    - name: TypeScript Check
      run: yarn tsc
    - run: yarn build
   